export const data = {
  name: 'Animals & Nature',
  emojis: [
    { emoji: '🐶', keywords: ['dog', 'puppy', 'pet', 'animal', 'cute'] },
    { emoji: '🐱', keywords: ['cat', 'kitten', 'pet', 'animal', 'cute'] },
    { emoji: '🐭', keywords: ['mouse', 'rodent', 'small', 'animal'] },
    { emoji: '🐹', keywords: ['hamster', 'pet', 'rodent', 'cute', 'small'] },
    { emoji: '🐰', keywords: ['rabbit', 'bunny', 'easter', 'cute', 'hop'] },
    { emoji: '🦊', keywords: ['fox', 'cunning', 'orange', 'wild', 'clever'] },
    { emoji: '🐻', keywords: ['bear', 'teddy', 'cute', 'strong', 'forest'] },
    { emoji: '🐼', keywords: ['panda', 'bear', 'cute', 'china', 'bamboo'] },
    { emoji: '🐨', keywords: ['koala', 'australia', 'cute', 'sleepy', 'eucalyptus'] },
    { emoji: '🐯', keywords: ['tiger', 'wild', 'stripes', 'fierce', 'jungle'] },
    { emoji: '🦁', keywords: ['lion', 'king', 'mane', 'wild', 'roar'] },
    { emoji: '🐮', keywords: ['cow', 'milk', 'farm', 'moo', 'cattle'] },
    { emoji: '🐷', keywords: ['pig', 'farm', 'oink', 'pink', 'cute'] },
    { emoji: '🐸', keywords: ['frog', 'green', 'pond', 'ribbit', 'jump'] },
    { emoji: '🐵', keywords: ['monkey', 'banana', 'jungle', 'playful', 'swing'] },
    { emoji: '🙈', keywords: ['see', 'no', 'evil', 'monkey', 'hide', 'embarrassed'] },
    { emoji: '🙉', keywords: ['hear', 'no', 'evil', 'monkey', 'deaf', 'ignore'] },
    { emoji: '🙊', keywords: ['speak', 'no', 'evil', 'monkey', 'quiet', 'secret'] },
    { emoji: '🐒', keywords: ['monkey', 'banana', 'jungle', 'climb', 'wild'] },
    { emoji: '🦍', keywords: ['gorilla', 'strong', 'jungle', 'ape', 'powerful'] },
    { emoji: '🐺', keywords: ['wolf', 'howl', 'wild', 'pack', 'moon'] },
    { emoji: '🐴', keywords: ['horse', 'pony', 'gallop', 'farm', 'ride'] },
    { emoji: '🦄', keywords: ['unicorn', 'magic', 'rainbow', 'fantasy', 'horn'] },
    { emoji: '🐝', keywords: ['bee', 'honey', 'buzz', 'flower', 'work'] },
    { emoji: '🐛', keywords: ['bug', 'insect', 'caterpillar', 'crawl', 'small'] },
    { emoji: '🦋', keywords: ['butterfly', 'beautiful', 'colorful', 'transformation', 'fly'] },
    { emoji: '🐌', keywords: ['snail', 'slow', 'shell', 'slimy', 'garden'] },
    { emoji: '🐞', keywords: ['lady', 'bug', 'beetle', 'red', 'spots'] },
    { emoji: '🐜', keywords: ['ant', 'work', 'colony', 'small', 'strong'] },
    { emoji: '🦟', keywords: ['mosquito', 'bite', 'annoying', 'buzz', 'blood'] },
    { emoji: '🕷️', keywords: ['spider', 'web', 'scary', 'eight', 'legs'] },
    { emoji: '🦂', keywords: ['scorpion', 'sting', 'desert', 'dangerous', 'tail'] },
    { emoji: '🐢', keywords: ['turtle', 'slow', 'shell', 'green', 'reptile'] },
    { emoji: '🐍', keywords: ['snake', 'slither', 'reptile', 'dangerous', 'coil'] },
    { emoji: '🦎', keywords: ['lizard', 'gecko', 'reptile', 'wall', 'green'] },
    { emoji: '🐙', keywords: ['octopus', 'tentacles', 'ocean', 'smart', 'eight'] },
    { emoji: '🦑', keywords: ['squid', 'ocean', 'tentacles', 'ink', 'sea'] },
    { emoji: '🦐', keywords: ['shrimp', 'seafood', 'ocean', 'small', 'crustacean'] },
    { emoji: '🦀', keywords: ['crab', 'ocean', 'claws', 'beach', 'sideways'] },
    { emoji: '🐠', keywords: ['fish', 'tropical', 'colorful', 'ocean', 'swim'] },
    { emoji: '🐟', keywords: ['fish', 'swim', 'water', 'ocean', 'seafood'] },
    { emoji: '🦈', keywords: ['shark', 'dangerous', 'ocean', 'teeth', 'predator'] },
    { emoji: '🐳', keywords: ['whale', 'ocean', 'large', 'mammal', 'spout'] },
    { emoji: '🐋', keywords: ['whale', 'ocean', 'large', 'blue', 'song'] },
    { emoji: '🐬', keywords: ['dolphin', 'smart', 'ocean', 'playful', 'jump'] },
    { emoji: '🐘', keywords: ['elephant', 'large', 'trunk', 'memory', 'africa'] },
    { emoji: '🦏', keywords: ['rhino', 'horn', 'africa', 'heavy', 'charge'] },
    { emoji: '🦛', keywords: ['hippo', 'water', 'large', 'africa', 'mouth'] },
    { emoji: '🐆', keywords: ['leopard', 'spots', 'wild', 'fast', 'hunter'] },
    { emoji: '🦓', keywords: ['zebra', 'stripes', 'africa', 'black', 'white'] },
    { emoji: '🦒', keywords: ['giraffe', 'tall', 'neck', 'africa', 'spots'] },
    { emoji: '🐃', keywords: ['water', 'buffalo', 'horns', 'strong', 'farm'] },
    { emoji: '🐂', keywords: ['ox', 'strong', 'farm', 'bull', 'horns'] },
    { emoji: '🐄', keywords: ['cow', 'farm', 'milk', 'moo', 'spots'] },
    { emoji: '🐎', keywords: ['horse', 'racing', 'fast', 'gallop', 'brown'] },
    { emoji: '🐖', keywords: ['pig', 'farm', 'pink', 'mud', 'oink'] },
    { emoji: '🐗', keywords: ['boar', 'wild', 'pig', 'tusks', 'forest'] },
    { emoji: '🐏', keywords: ['ram', 'sheep', 'horns', 'wool', 'farm'] },
    { emoji: '🐑', keywords: ['sheep', 'wool', 'farm', 'fluffy', 'baa'] },
    { emoji: '🐐', keywords: ['goat', 'horns', 'farm', 'climb', 'beard'] },
    { emoji: '🦌', keywords: ['deer', 'antlers', 'forest', 'graceful', 'bambi'] },
    { emoji: '🦘', keywords: ['kangaroo', 'australia', 'hop', 'pouch', 'jump'] },
    { emoji: '🦥', keywords: ['sloth', 'slow', 'lazy', 'tree', 'hang'] },
    { emoji: '🦦', keywords: ['otter', 'water', 'playful', 'cute', 'swim'] },
    { emoji: '🦨', keywords: ['skunk', 'smell', 'stripe', 'spray', 'black'] },
    { emoji: '🦡', keywords: ['badger', 'burrow', 'stripe', 'dig', 'fierce'] },
  ],
};
