export const data = {
  name: 'Buildings & Places',
  emojis: [
    { emoji: '🏠', keywords: ['house', 'home', 'building', 'residential'] },
    { emoji: '🏡', keywords: ['house', 'garden', 'home', 'suburban', 'residential'] },
    { emoji: '🏘️', keywords: ['houses', 'neighborhood', 'residential', 'community'] },
    { emoji: '🏚️', keywords: ['derelict', 'house', 'abandoned', 'old', 'broken'] },
    { emoji: '🏗️', keywords: ['building', 'construction', 'crane', 'work', 'site'] },
    { emoji: '🏭', keywords: ['factory', 'industrial', 'manufacturing', 'pollution'] },
    { emoji: '🏢', keywords: ['office', 'building', 'business', 'corporate', 'work'] },
    { emoji: '🏬', keywords: ['department', 'store', 'shopping', 'mall', 'retail'] },
    { emoji: '🏣', keywords: ['japanese', 'post', 'office', 'building'] },
    { emoji: '🏤', keywords: ['european', 'post', 'office', 'building'] },
    { emoji: '🏥', keywords: ['hospital', 'medical', 'health', 'emergency', 'doctor'] },
    { emoji: '🏦', keywords: ['bank', 'money', 'financial', 'institution'] },
    { emoji: '🏨', keywords: ['hotel', 'accommodation', 'travel', 'vacation'] },
    { emoji: '🏩', keywords: ['love', 'hotel', 'romantic', 'heart'] },
    { emoji: '🏪', keywords: ['convenience', 'store', 'shop', 'retail'] },
    { emoji: '🏫', keywords: ['school', 'education', 'learning', 'students'] },
    { emoji: '🏰', keywords: ['castle', 'fortress', 'medieval', 'royal', 'palace'] },
    { emoji: '🗼', keywords: ['tokyo', 'tower', 'landmark', 'tall', 'structure'] },
    { emoji: '🗽', keywords: ['statue', 'liberty', 'new', 'york', 'freedom'] },
    { emoji: '⛪', keywords: ['church', 'religion', 'christian', 'worship'] },
    { emoji: '🕌', keywords: ['mosque', 'islam', 'muslim', 'worship', 'religion'] },
    { emoji: '🛕', keywords: ['hindu', 'temple', 'religion', 'worship'] },
    { emoji: '🕍', keywords: ['synagogue', 'jewish', 'religion', 'worship'] },
    { emoji: '⛩️', keywords: ['shinto', 'shrine', 'japanese', 'religion'] },
    { emoji: '🕋', keywords: ['kaaba', 'mecca', 'islam', 'pilgrimage'] },
    { emoji: '⛲', keywords: ['fountain', 'water', 'park', 'decoration'] },
    { emoji: '⛺', keywords: ['tent', 'camping', 'outdoor', 'adventure'] },
    { emoji: '🌁', keywords: ['foggy', 'city', 'skyline', 'mist', 'weather'] },
    { emoji: '🌃', keywords: ['night', 'city', 'lights', 'urban', 'skyline'] },
    { emoji: '🏙️', keywords: ['cityscape', 'urban', 'buildings', 'skyline'] },
    { emoji: '🌄', keywords: ['sunrise', 'mountains', 'morning', 'landscape'] },
    { emoji: '🌅', keywords: ['sunrise', 'ocean', 'morning', 'beach'] },
    { emoji: '🌆', keywords: ['cityscape', 'dusk', 'evening', 'sunset'] },
    { emoji: '🌇', keywords: ['sunset', 'city', 'evening', 'buildings'] },
    { emoji: '🌉', keywords: ['bridge', 'night', 'lights', 'architecture'] },
    { emoji: '♨️', keywords: ['hot', 'springs', 'spa', 'relax', 'steam'] },
    { emoji: '🎠', keywords: ['carousel', 'horse', 'amusement', 'park', 'fun'] },
    { emoji: '🎡', keywords: ['ferris', 'wheel', 'amusement', 'park', 'ride'] },
    { emoji: '🎢', keywords: ['roller', 'coaster', 'amusement', 'park', 'thrill'] },
    { emoji: '💈', keywords: ['barber', 'pole', 'haircut', 'salon', 'shop'] },
    { emoji: '🎪', keywords: ['circus', 'tent', 'entertainment', 'show', 'fun'] },
    { emoji: '🛏️', keywords: ['bed', 'sleep', 'hotel', 'rest', 'bedroom'] },
    { emoji: '🛋️', keywords: ['couch', 'lamp', 'furniture', 'living', 'room'] },
    { emoji: '🪑', keywords: ['chair', 'sit', 'furniture', 'seat'] },
    { emoji: '🚪', keywords: ['door', 'entrance', 'exit', 'opening'] },
    { emoji: '🪟', keywords: ['window', 'view', 'glass', 'opening'] },
    { emoji: '🪜', keywords: ['ladder', 'climb', 'steps', 'up'] },
  ],
};
