export const data = {
	name: 'Flags',
	emojis: [
		{ emoji: '🏳️', keywords: ['flag', 'white', 'flag', 'surrender'] },
		{ emoji: '🏴', keywords: ['flag', 'black', 'flag'] },
		{ emoji: '🇪🇺', keywords: ['flag', 'european', 'union', 'eu'] },
		{ emoji: '🇺🇳', keywords: ['flag', 'united', 'nations', 'un'] },
		{ emoji: '🇺🇸', keywords: ['flag', 'united', 'states', 'usa', 'america'] },
		{ emoji: '🇨🇦', keywords: ['flag', 'canada', 'ca'] },
		{ emoji: '🇲🇽', keywords: ['flag', 'mexico', 'mx'] },
		{ emoji: '🇧🇷', keywords: ['flag', 'brazil', 'br'] },
		{ emoji: '🇦🇷', keywords: ['flag', 'argentina', 'ar'] },
		{ emoji: '🇨🇱', keywords: ['flag', 'chile', 'cl'] },
		{ emoji: '🇨🇴', keywords: ['flag', 'colombia', 'co'] },
		{ emoji: '🇵🇪', keywords: ['flag', 'peru', 'pe'] },
		{ emoji: '🇻🇪', keywords: ['flag', 'venezuela', 've'] },
		{ emoji: '🇪🇨', keywords: ['flag', 'ecuador', 'ec'] },
		{ emoji: '🇺🇾', keywords: ['flag', 'uruguay', 'uy'] },
		{ emoji: '🇵🇾', keywords: ['flag', 'paraguay', 'py'] },
		{ emoji: '🇧🇴', keywords: ['flag', 'bolivia', 'bo'] },
		{ emoji: '🇬🇹', keywords: ['flag', 'guatemala', 'gt'] },
		{ emoji: '🇭🇳', keywords: ['flag', 'honduras', 'hn'] },
		{ emoji: '🇸🇻', keywords: ['flag', 'el', 'salvador', 'sv'] },
		{ emoji: '🇳🇮', keywords: ['flag', 'nicaragua', 'ni'] },
		{ emoji: '🇨🇷', keywords: ['flag', 'costa', 'rica', 'cr'] },
		{ emoji: '🇵🇦', keywords: ['flag', 'panama', 'pa'] },
		{ emoji: '🇨🇺', keywords: ['flag', 'cuba', 'cu'] },
		{ emoji: '🇩🇴', keywords: ['flag', 'dominican', 'republic', 'do'] },
		{ emoji: '🇭🇹', keywords: ['flag', 'haiti', 'ht'] },
		{ emoji: '🇯🇲', keywords: ['flag', 'jamaica', 'jm'] },
		{ emoji: '🇧🇧', keywords: ['flag', 'barbados', 'bb'] },
		{ emoji: '🇧🇸', keywords: ['flag', 'bahamas', 'bs'] },
		{ emoji: '🇹🇹', keywords: ['flag', 'trinidad', 'tobago', 'tt'] },
		{ emoji: '🇦🇬', keywords: ['flag', 'antigua', 'barbuda', 'ag'] },
		{ emoji: '🇩🇲', keywords: ['flag', 'dominica', 'dm'] },
		{ emoji: '🇬🇩', keywords: ['flag', 'grenada', 'gd'] },
		{ emoji: '🇰🇳', keywords: ['flag', 'saint', 'kitts', 'nevis', 'kn'] },
		{ emoji: '🇱🇨', keywords: ['flag', 'saint', 'lucia', 'lc'] },
		{ emoji: '🇻🇨', keywords: ['flag', 'saint', 'vincent', 'grenadines', 'vc'] },
		{ emoji: '🇬🇾', keywords: ['flag', 'guyana', 'gy'] },
		{ emoji: '🇸🇷', keywords: ['flag', 'suriname', 'sr'] },
		{ emoji: '🇵🇷', keywords: ['flag', 'puerto', 'rico', 'pr'] },
		{ emoji: '🇬🇧', keywords: ['flag', 'united', 'kingdom', 'uk', 'gb'] },
		{ emoji: '🇮🇪', keywords: ['flag', 'ireland', 'ie'] },
		{ emoji: '🇫🇷', keywords: ['flag', 'france', 'fr'] },
		{ emoji: '🇷🇪', keywords: ['flag', 'reunion', 'réunion', 're'] },
		{ emoji: '🇩🇪', keywords: ['flag', 'germany', 'de'] },
		{ emoji: '🇪🇸', keywords: ['flag', 'spain', 'es'] },
		{ emoji: '🇮🇹', keywords: ['flag', 'italy', 'it'] },
		{ emoji: '🇵🇹', keywords: ['flag', 'portugal', 'pt'] },
		{ emoji: '🇳🇱', keywords: ['flag', 'netherlands', 'nl'] },
		{ emoji: '🇧🇪', keywords: ['flag', 'belgium', 'be'] },
		{ emoji: '🇱🇺', keywords: ['flag', 'luxembourg', 'lu'] },
		{ emoji: '🇨🇭', keywords: ['flag', 'switzerland', 'ch'] },
		{ emoji: '🇦🇹', keywords: ['flag', 'austria', 'at'] },
		{ emoji: '🇵🇱', keywords: ['flag', 'poland', 'pl'] },
		{ emoji: '🇨🇿', keywords: ['flag', 'czech', 'republic', 'cz'] },
		{ emoji: '🇸🇰', keywords: ['flag', 'slovakia', 'sk'] },
		{ emoji: '🇭🇺', keywords: ['flag', 'hungary', 'hu'] },
		{ emoji: '🇷🇴', keywords: ['flag', 'romania', 'ro'] },
		{ emoji: '🇧🇬', keywords: ['flag', 'bulgaria', 'bg'] },
		{ emoji: '🇭🇷', keywords: ['flag', 'croatia', 'hr'] },
		{ emoji: '🇸🇮', keywords: ['flag', 'slovenia', 'si'] },
		{ emoji: '🇬🇷', keywords: ['flag', 'greece', 'gr'] },
		{ emoji: '🇹🇷', keywords: ['flag', 'turkey', 'tr'] },
		{ emoji: '🇷🇺', keywords: ['flag', 'russia', 'ru'] },
		{ emoji: '🇺🇦', keywords: ['flag', 'ukraine', 'ua'] },
		{ emoji: '🇧🇾', keywords: ['flag', 'belarus', 'by'] },
		{ emoji: '🇫🇮', keywords: ['flag', 'finland', 'fi'] },
		{ emoji: '🇸🇪', keywords: ['flag', 'sweden', 'se'] },
		{ emoji: '🇳🇴', keywords: ['flag', 'norway', 'no'] },
		{ emoji: '🇩🇰', keywords: ['flag', 'denmark', 'dk'] },
		{ emoji: '🇮🇸', keywords: ['flag', 'iceland', 'is'] },
		{ emoji: '🇪🇪', keywords: ['flag', 'estonia', 'ee'] },
		{ emoji: '🇱🇻', keywords: ['flag', 'latvia', 'lv'] },
		{ emoji: '🇱🇹', keywords: ['flag', 'lithuania', 'lt'] },
		{ emoji: '🇲🇹', keywords: ['flag', 'malta', 'mt'] },
		{ emoji: '🇨🇾', keywords: ['flag', 'cyprus', 'cy'] },
		{ emoji: '🇦🇱', keywords: ['flag', 'albania', 'al'] },
		{ emoji: '🇷🇸', keywords: ['flag', 'serbia', 'rs'] },
		{ emoji: '🇲🇪', keywords: ['flag', 'montenegro', 'me'] },
		{ emoji: '🇧🇦', keywords: ['flag', 'bosnia', 'herzegovina', 'ba'] },
		{ emoji: '🇲🇰', keywords: ['flag', 'north', 'macedonia', 'mk'] },
		{ emoji: '🇦🇲', keywords: ['flag', 'armenia', 'am'] },
		{ emoji: '🇬🇪', keywords: ['flag', 'georgia', 'ge'] },
		{ emoji: '🇦🇿', keywords: ['flag', 'azerbaijan', 'az'] },
		{ emoji: '🇰🇿', keywords: ['flag', 'kazakhstan', 'kz'] },
		{ emoji: '🇰🇬', keywords: ['flag', 'kyrgyzstan', 'kg'] },
		{ emoji: '🇺🇿', keywords: ['flag', 'uzbekistan', 'uz'] },
		{ emoji: '🇹🇯', keywords: ['flag', 'tajikistan', 'tj'] },
		{ emoji: '🇹🇲', keywords: ['flag', 'turkmenistan', 'tm'] },
		{ emoji: '🇵🇰', keywords: ['flag', 'pakistan', 'pk'] },
		{ emoji: '🇮🇳', keywords: ['flag', 'india', 'in'] },
		{ emoji: '🇧🇩', keywords: ['flag', 'bangladesh', 'bd'] },
		{ emoji: '🇳🇵', keywords: ['flag', 'nepal', 'np'] },
		{ emoji: '🇱🇰', keywords: ['flag', 'sri', 'lanka', 'lk'] },
		{ emoji: '🇲🇲', keywords: ['flag', 'myanmar', 'mm'] },
		{ emoji: '🇹🇭', keywords: ['flag', 'thailand', 'th'] },
		{ emoji: '🇻🇳', keywords: ['flag', 'vietnam', 'vn'] },
		{ emoji: '🇰🇭', keywords: ['flag', 'cambodia', 'kh'] },
		{ emoji: '🇱🇦', keywords: ['flag', 'laos', 'la'] },
		{ emoji: '🇲🇾', keywords: ['flag', 'malaysia', 'my'] },
		{ emoji: '🇸🇬', keywords: ['flag', 'singapore', 'sg'] },
		{ emoji: '🇮🇩', keywords: ['flag', 'indonesia', 'id'] },
		{ emoji: '🇵🇭', keywords: ['flag', 'philippines', 'ph'] },
		{ emoji: '🇯🇵', keywords: ['flag', 'japan', 'jp'] },
		{ emoji: '🇰🇷', keywords: ['flag', 'south', 'korea', 'kr'] },
		{ emoji: '🇨🇳', keywords: ['flag', 'china', 'cn'] },
		{ emoji: '🇹🇼', keywords: ['flag', 'taiwan', 'tw'] },
		{ emoji: '🇭🇰', keywords: ['flag', 'hong', 'kong', 'hk'] },
		{ emoji: '🇲🇴', keywords: ['flag', 'macao', 'mo'] },
		{ emoji: '🇦🇺', keywords: ['flag', 'australia', 'au'] },
		{ emoji: '🇳🇿', keywords: ['flag', 'new', 'zealand', 'nz'] },
		{ emoji: '🇫🇯', keywords: ['flag', 'fiji', 'fj'] },
		{ emoji: '🇵🇬', keywords: ['flag', 'papua', 'new', 'guinea', 'pg'] },
		{ emoji: '🇸🇧', keywords: ['flag', 'solomon', 'islands', 'sb'] },
		{ emoji: '🇻🇺', keywords: ['flag', 'vanuatu', 'vu'] },
		{ emoji: '🇼🇸', keywords: ['flag', 'samoa', 'ws'] },
		{ emoji: '🇹🇴', keywords: ['flag', 'tonga', 'to'] },
		{ emoji: '🇹🇻', keywords: ['flag', 'tuvalu', 'tv'] },
		{ emoji: '🇰🇮', keywords: ['flag', 'kiribati', 'ki'] },
		{ emoji: '🇳🇷', keywords: ['flag', 'nauru', 'nr'] },
		{ emoji: '🇵🇼', keywords: ['flag', 'palau', 'pw'] },
		{ emoji: '🇲🇭', keywords: ['flag', 'marshall', 'islands', 'mh'] },
		{ emoji: '🇿🇦', keywords: ['flag', 'south', 'africa', 'za'] },
		{ emoji: '🇳🇬', keywords: ['flag', 'nigeria', 'ng'] },
		{ emoji: '🇪🇬', keywords: ['flag', 'egypt', 'eg'] },
		{ emoji: '🇲🇦', keywords: ['flag', 'morocco', 'ma'] },
		{ emoji: '🇹🇳', keywords: ['flag', 'tunisia', 'tn'] },
		{ emoji: '🇩🇿', keywords: ['flag', 'algeria', 'dz'] },
		{ emoji: '🇱🇾', keywords: ['flag', 'libya', 'ly'] },
		{ emoji: '🇸🇩', keywords: ['flag', 'sudan', 'sd'] },
		{ emoji: '🇸🇸', keywords: ['flag', 'south', 'sudan', 'ss'] },
		{ emoji: '🇪🇹', keywords: ['flag', 'ethiopia', 'et'] },
		{ emoji: '🇰🇪', keywords: ['flag', 'kenya', 'ke'] },
		{ emoji: '🇺🇬', keywords: ['flag', 'uganda', 'ug'] },
		{ emoji: '🇹🇿', keywords: ['flag', 'tanzania', 'tz'] },
		{ emoji: '🇷🇼', keywords: ['flag', 'rwanda', 'rw'] },
		{ emoji: '🇧🇮', keywords: ['flag', 'burundi', 'bi'] },
		{ emoji: '🇨🇬', keywords: ['flag', 'congo', 'cg'] },
		{ emoji: '🇨🇩', keywords: ['flag', 'dr', 'congo', 'cd'] },
		{ emoji: '🇨🇲', keywords: ['flag', 'cameroon', 'cm'] },
		{ emoji: '🇬🇭', keywords: ['flag', 'ghana', 'gh'] },
		{ emoji: '🇨🇮', keywords: ['flag', 'cote', 'ivoire', 'ci'] },
		{ emoji: '🇸🇳', keywords: ['flag', 'senegal', 'sn'] },
		{ emoji: '🇬🇲', keywords: ['flag', 'gambia', 'gm'] },
		{ emoji: '🇱🇷', keywords: ['flag', 'liberia', 'lr'] },
		{ emoji: '🇸🇱', keywords: ['flag', 'sierra', 'leone', 'sl'] },
		{ emoji: '🇬🇳', keywords: ['flag', 'guinea', 'gn'] },
		{ emoji: '🇬🇼', keywords: ['flag', 'guinea', 'bissau', 'gw'] },
		{ emoji: '🇧🇫', keywords: ['flag', 'burkina', 'faso', 'bf'] },
		{ emoji: '🇳🇪', keywords: ['flag', 'niger', 'ne'] },
		{ emoji: '🇲🇱', keywords: ['flag', 'mali', 'ml'] },
		{ emoji: '🇲🇷', keywords: ['flag', 'mauritania', 'mr'] },
		{ emoji: '🇧🇯', keywords: ['flag', 'benin', 'bj'] },
		{ emoji: '🇹🇬', keywords: ['flag', 'togo', 'tg'] },
		{ emoji: '🇨🇻', keywords: ['flag', 'cape', 'verde', 'cv'] },
		{ emoji: '🇸🇹', keywords: ['flag', 'sao', 'tome', 'principe', 'st'] },
		{ emoji: '🇦🇴', keywords: ['flag', 'angola', 'ao'] },
		{ emoji: '🇲🇿', keywords: ['flag', 'mozambique', 'mz'] },
		{ emoji: '🇿🇲', keywords: ['flag', 'zambia', 'zm'] },
		{ emoji: '🇿🇼', keywords: ['flag', 'zimbabwe', 'zw'] },
		{ emoji: '🇧🇼', keywords: ['flag', 'botswana', 'bw'] },
		{ emoji: '🇳🇦', keywords: ['flag', 'namibia', 'na'] },
		{ emoji: '🇱🇸', keywords: ['flag', 'lesotho', 'ls'] },
		{ emoji: '🇸🇿', keywords: ['flag', 'eswatini', 'sz'] },
		{ emoji: '🇲🇼', keywords: ['flag', 'malawi', 'mw'] },
		{ emoji: '🇲🇬', keywords: ['flag', 'madagascar', 'mg'] },
		{ emoji: '🇲🇺', keywords: ['flag', 'mauritius', 'mu'] },
		{ emoji: '🇸🇨', keywords: ['flag', 'seychelles', 'sc'] },
		{ emoji: '🇰🇼', keywords: ['flag', 'kuwait', 'kw'] },
		{ emoji: '🇶🇦', keywords: ['flag', 'qatar', 'qa'] },
		{ emoji: '🇧🇭', keywords: ['flag', 'bahrain', 'bh'] },
		{ emoji: '🇴🇲', keywords: ['flag', 'oman', 'om'] },
		{ emoji: '🇦🇪', keywords: ['flag', 'uae', 'emirates', 'ae'] },
		{ emoji: '🇸🇦', keywords: ['flag', 'saudi', 'arabia', 'sa'] },
		{ emoji: '🇾🇪', keywords: ['flag', 'yemen', 'ye'] },
		{ emoji: '🇯🇴', keywords: ['flag', 'jordan', 'jo'] },
		{ emoji: '🇮🇱', keywords: ['flag', 'israel', 'il'] },
		{ emoji: '🇵🇸', keywords: ['flag', 'palestine', 'ps'] },
		{ emoji: '🏳️‍🌈', keywords: ['flag', 'rainbow', 'pride', 'lgbt'] },
		{ emoji: '🏳️‍⚧️', keywords: ['flag', 'transgender', 'pride', 'lgbt'] },
		{ emoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', keywords: ['flag', 'england', 'gb-eng'] },
		{ emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', keywords: ['flag', 'scotland', 'gb-sct'] },
		{ emoji: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', keywords: ['flag', 'wales', 'gb-wls'] },

		{ emoji: '🇦🇨', keywords: ['flag', 'ascension', 'island', 'ac'] },
		{ emoji: '🇦🇩', keywords: ['flag', 'andorra', 'ad'] },
		{ emoji: '🇦🇫', keywords: ['flag', 'afghanistan', 'af'] },
		{ emoji: '🇦🇮', keywords: ['flag', 'anguilla', 'ai'] },
		{ emoji: '🇦🇶', keywords: ['flag', 'antarctica', 'aq'] },
		{ emoji: '🇦🇸', keywords: ['flag', 'american', 'samoa', 'as'] },
		{ emoji: '🇦🇼', keywords: ['flag', 'aruba', 'aw'] },
		{ emoji: '🇦🇽', keywords: ['flag', 'land', 'islands', 'ax'] },
		{ emoji: '🇧🇱', keywords: ['flag', 'st', 'barth', 'lemy', 'bl'] },
		{ emoji: '🇧🇲', keywords: ['flag', 'bermuda', 'bm'] },
		{ emoji: '🇧🇳', keywords: ['flag', 'brunei', 'bn'] },
		{ emoji: '🇧🇶', keywords: ['flag', 'caribbean', 'netherlands', 'bq'] },
		{ emoji: '🇧🇹', keywords: ['flag', 'bhutan', 'bt'] },
		{ emoji: '🇧🇻', keywords: ['flag', 'bouvet', 'island', 'bv'] },
		{ emoji: '🇧🇿', keywords: ['flag', 'belize', 'bz'] },
		{ emoji: '🇨🇨', keywords: ['flag', 'cocos', 'keeling', 'islands', 'cc'] },
		{ emoji: '🇨🇫', keywords: ['flag', 'central', 'african', 'republic', 'cf'] },
		{ emoji: '🇨🇰', keywords: ['flag', 'cook', 'islands', 'ck'] },
		{ emoji: '🇨🇵', keywords: ['flag', 'clipperton', 'island', 'cp'] },
		{ emoji: '🇨🇼', keywords: ['flag', 'cura', 'ao', 'cw'] },
		{ emoji: '🇨🇽', keywords: ['flag', 'christmas', 'island', 'cx'] },
		{ emoji: '🇩🇬', keywords: ['flag', 'diego', 'garcia', 'dg'] },
		{ emoji: '🇩🇯', keywords: ['flag', 'djibouti', 'dj'] },
		{ emoji: '🇪🇦', keywords: ['flag', 'ceuta', 'melilla', 'ea'] },
		{ emoji: '🇪🇭', keywords: ['flag', 'western', 'sahara', 'eh'] },
		{ emoji: '🇪🇷', keywords: ['flag', 'eritrea', 'er'] },
		{ emoji: '🇫🇰', keywords: ['flag', 'falkland', 'islands', 'fk'] },
		{ emoji: '🇫🇲', keywords: ['flag', 'micronesia', 'fm'] },
		{ emoji: '🇫🇴', keywords: ['flag', 'faroe', 'islands', 'fo'] },
		{ emoji: '🇬🇦', keywords: ['flag', 'gabon', 'ga'] },
		{ emoji: '🇬🇫', keywords: ['flag', 'french', 'guiana', 'gf'] },
		{ emoji: '🇬🇬', keywords: ['flag', 'guernsey', 'gg'] },
		{ emoji: '🇬🇮', keywords: ['flag', 'gibraltar', 'gi'] },
		{ emoji: '🇬🇱', keywords: ['flag', 'greenland', 'gl'] },
		{ emoji: '🇬🇵', keywords: ['flag', 'guadeloupe', 'gp'] },
		{ emoji: '🇬🇶', keywords: ['flag', 'equatorial', 'guinea', 'gq'] },
		{ emoji: '🇬🇸', keywords: ['flag', 'south', 'georgia', 'south', 'sandwich', 'islands', 'gs'] },
		{ emoji: '🇬🇺', keywords: ['flag', 'guam', 'gu'] },
		{ emoji: '🇭🇲', keywords: ['flag', 'heard', 'mcdonald', 'islands', 'hm'] },
		{ emoji: '🇮🇨', keywords: ['flag', 'canary', 'islands', 'ic'] },
		{ emoji: '🇮🇲', keywords: ['flag', 'isle', 'of', 'man', 'im'] },
		{ emoji: '🇮🇴', keywords: ['flag', 'british', 'indian', 'ocean', 'territory', 'io'] },
		{ emoji: '🇮🇶', keywords: ['flag', 'iraq', 'iq'] },
		{ emoji: '🇮🇷', keywords: ['flag', 'iran', 'ir'] },
		{ emoji: '🇯🇪', keywords: ['flag', 'jersey', 'je'] },
		{ emoji: '🇰🇲', keywords: ['flag', 'comoros', 'km'] },
		{ emoji: '🇰🇵', keywords: ['flag', 'north', 'korea', 'kp'] },
		{ emoji: '🇰🇾', keywords: ['flag', 'cayman', 'islands', 'ky'] },
		{ emoji: '🇱🇧', keywords: ['flag', 'lebanon', 'lb'] },
		{ emoji: '🇱🇮', keywords: ['flag', 'liechtenstein', 'li'] },
		{ emoji: '🇲🇨', keywords: ['flag', 'monaco', 'mc'] },
		{ emoji: '🇲🇩', keywords: ['flag', 'moldova', 'md'] },
		{ emoji: '🇲🇫', keywords: ['flag', 'st', 'martin', 'mf'] },
		{ emoji: '🇲🇳', keywords: ['flag', 'mongolia', 'mn'] },
		{ emoji: '🇲🇵', keywords: ['flag', 'northern', 'mariana', 'islands', 'mp'] },
		{ emoji: '🇲🇶', keywords: ['flag', 'martinique', 'mq'] },
		{ emoji: '🇲🇸', keywords: ['flag', 'montserrat', 'ms'] },
		{ emoji: '🇲🇻', keywords: ['flag', 'maldives', 'mv'] },
		{ emoji: '🇳🇨', keywords: ['flag', 'new', 'caledonia', 'nc'] },
		{ emoji: '🇳🇫', keywords: ['flag', 'norfolk', 'island', 'nf'] },
		{ emoji: '🇳🇺', keywords: ['flag', 'niue', 'nu'] },
		{ emoji: '🇵🇫', keywords: ['flag', 'french', 'polynesia', 'pf'] },
		{ emoji: '🇵🇲', keywords: ['flag', 'st', 'pierre', 'miquelon', 'pm'] },
		{ emoji: '🇵🇳', keywords: ['flag', 'pitcairn', 'islands', 'pn'] },
		{ emoji: '🇸🇭', keywords: ['flag', 'st', 'helena', 'sh'] },
		{ emoji: '🇸🇯', keywords: ['flag', 'svalbard', 'jan', 'mayen', 'sj'] },
		{ emoji: '🇸🇲', keywords: ['flag', 'san', 'marino', 'sm'] },
		{ emoji: '🇸🇴', keywords: ['flag', 'somalia', 'so'] },
		{ emoji: '🇸🇽', keywords: ['flag', 'sint', 'maarten', 'sx'] },
		{ emoji: '🇸🇾', keywords: ['flag', 'syria', 'sy'] },
		{ emoji: '🇹🇦', keywords: ['flag', 'tristan', 'da', 'cunha', 'ta'] },
		{ emoji: '🇹🇨', keywords: ['flag', 'turks', 'caicos', 'islands', 'tc'] },
		{ emoji: '🇹🇩', keywords: ['flag', 'chad', 'td'] },
		{ emoji: '🇹🇫', keywords: ['flag', 'french', 'southern', 'territories', 'tf'] },
		{ emoji: '🇹🇰', keywords: ['flag', 'tokelau', 'tk'] },
		{ emoji: '🇹🇱', keywords: ['flag', 'timor', 'leste', 'tl'] },
		{ emoji: '🇺🇲', keywords: ['flag', 'u', 's', 'outlying', 'islands', 'um'] },
		{ emoji: '🇻🇦', keywords: ['flag', 'vatican', 'city', 'va'] },
		{ emoji: '🇻🇬', keywords: ['flag', 'british', 'virgin', 'islands', 'vg'] },
		{ emoji: '🇻🇮', keywords: ['flag', 'u', 's', 'virgin', 'islands', 'vi'] },
		{ emoji: '🇼🇫', keywords: ['flag', 'wallis', 'futuna', 'wf'] },
		{ emoji: '🇽🇰', keywords: ['flag', 'kosovo', 'xk'] },
		{ emoji: '🇾🇹', keywords: ['flag', 'mayotte', 'yt'] },
	],
};
