export const data = {
	name: 'Gestures',
	emojis: [
		{ emoji: '👍', keywords: ['thumbs', 'up', 'good', 'yes', 'ok', 'approve'] },
		{ emoji: '👎', keywords: ['thumbs', 'down', 'bad', 'no', 'disapprove', 'dislike'] },
		{ emoji: '👌', keywords: ['ok', 'perfect', 'good', 'fine', 'excellent'] },
		{ emoji: '🤌', keywords: ['pinched', 'fingers', 'italian', 'chef', 'kiss'] },
		{ emoji: '🤏', keywords: ['pinch', 'small', 'tiny', 'little', 'bit'] },
		{ emoji: '✌️', keywords: ['peace', 'victory', 'two', 'fingers', 'sign'] },
		{ emoji: '🤞', keywords: ['cross', 'fingers', 'luck', 'hope', 'wish'] },
		{ emoji: '🤟', keywords: ['love', 'you', 'sign', 'language', 'hand'] },
		{ emoji: '🤘', keywords: ['rock', 'on', 'metal', 'horns', 'music'] },
		{ emoji: '🤙', keywords: ['call', 'me', 'hang', 'loose', 'shaka'] },
		{ emoji: '👈', keywords: ['point', 'left', 'finger', 'direction', 'that'] },
		{ emoji: '👉', keywords: ['point', 'right', 'finger', 'direction', 'this'] },
		{ emoji: '👆', keywords: ['point', 'up', 'finger', 'direction', 'above'] },
		{ emoji: '👇', keywords: ['point', 'down', 'finger', 'direction', 'below'] },
		{ emoji: '☝️', keywords: ['index', 'point', 'up', 'finger', 'one'] },
		{ emoji: '👋', keywords: ['wave', 'hello', 'goodbye', 'hi', 'bye'] },
		{ emoji: '🤚', keywords: ['raised', 'back', 'hand', 'stop', 'high', 'five'] },
		{ emoji: '🖐', keywords: ['hand', 'five', 'fingers', 'palm', 'stop'] },
		{ emoji: '✋', keywords: ['raised', 'hand', 'stop', 'high', 'five'] },
		{ emoji: '🖖', keywords: ['vulcan', 'spock', 'star', 'trek', 'live', 'long'] },
		{ emoji: '👏', keywords: ['clap', 'applause', 'bravo', 'good', 'job'] },
		{ emoji: '🙌', keywords: ['praise', 'celebration', 'hands', 'hooray', 'yay'] },
		{ emoji: '🤝', keywords: ['handshake', 'deal', 'agreement', 'partnership', 'hello'] },
		{ emoji: '👐', keywords: ['open', 'hands', 'hug', 'embrace', 'jazz'] },
		{ emoji: '🤲', keywords: ['palms', 'up', 'together', 'pray', 'ask'] },
		{ emoji: '🤜', keywords: ['right', 'facing', 'fist', 'punch', 'bump'] },
		{ emoji: '🤛', keywords: ['left', 'facing', 'fist', 'punch', 'bump'] },
		{ emoji: '✊', keywords: ['raised', 'fist', 'power', 'strength', 'solidarity'] },
		{ emoji: '👊', keywords: ['fist', 'bump', 'punch', 'knuckles', 'greeting'] },
		{ emoji: '🙏', keywords: ['folded', 'hands', 'pray', 'please', 'thank', 'you'] },
		{ emoji: '💪', keywords: ['flexed', 'bicep', 'strong', 'muscle', 'power'] },
		{ emoji: '🦵', keywords: ['leg', 'kick', 'limb'] },
		{ emoji: '🦶', keywords: ['foot', 'kick', 'stomp'] },
		{ emoji: '👂', keywords: ['ear', 'hear', 'listen', 'sound'] },
		{ emoji: '👃', keywords: ['nose', 'smell', 'sniff'] },
		{ emoji: '👀', keywords: ['eyes', 'look', 'see', 'watch'] },
		{ emoji: '👁️', keywords: ['eye', 'see', 'look', 'watch'] },
		{ emoji: '👄', keywords: ['mouth', 'lips', 'kiss', 'speak'] },
		{ emoji: '👅', keywords: ['tongue', 'lick', 'taste'] },
	],
};
