export const data = {
	name: 'Objects & Symbols',
	emojis: [
		{ emoji: '🎉', keywords: ['party', 'celebration', 'confetti', 'tada', 'congrats'] },
		{ emoji: '🎊', keywords: ['confetti', 'ball', 'party', 'celebration', 'festive'] },
		{ emoji: '✨', keywords: ['sparkles', 'stars', 'magic', 'shine', 'glitter'] },
		{ emoji: '🔥', keywords: ['fire', 'hot', 'burn', 'lit', 'flame'] },
		{ emoji: '💯', keywords: ['hundred', 'percent', 'perfect', 'score', 'complete'] },
		{ emoji: '⭐', keywords: ['star', 'favorite', 'rate', 'excellent', 'good'] },
		{ emoji: '🌟', keywords: ['glowing', 'star', 'shine', 'sparkle', 'bright'] },
		{ emoji: '⚡', keywords: ['lightning', 'bolt', 'thunder', 'electric', 'power'] },
		{ emoji: '💥', keywords: ['boom', 'explosion', 'burst', 'comic', 'crash'] },
		{ emoji: '💫', keywords: ['dizzy', 'star', 'sparkle', 'magic', 'cosmic'] },
		{ emoji: '☮️', keywords: ['peace', 'symbol', 'hippie', 'love', 'harmony'] },
		{ emoji: '✅', keywords: ['check', 'mark', 'done', 'complete', 'yes'] },
		{ emoji: '❌', keywords: ['cross', 'mark', 'wrong', 'no', 'error'] },
		{ emoji: '❓', keywords: ['question', 'mark', 'confused', 'help', 'what'] },
		{ emoji: '❗', keywords: ['exclamation', 'mark', 'important', 'alert', 'warning'] },
		{ emoji: '💡', keywords: ['bulb', 'idea', 'light', 'bright', 'innovation'] },
		{ emoji: '🔔', keywords: ['bell', 'notification', 'alert', 'ring'] },
		{ emoji: '🔕', keywords: ['bell', 'slash', 'silent', 'mute', 'quiet'] },

		{ emoji: '💎', keywords: ['diamond', 'gem', 'jewel', 'precious', 'sparkle'] },
		{ emoji: '🎁', keywords: ['gift', 'present', 'box', 'surprise', 'birthday'] },

		{ emoji: '🎭', keywords: ['performing', 'arts', 'theater', 'masks', 'drama'] },
		{ emoji: '🎨', keywords: ['artist', 'palette', 'paint', 'creative', 'art'] },
		{ emoji: '🎸', keywords: ['guitar', 'music', 'rock', 'instrument', 'song'] },
		{ emoji: '🎵', keywords: ['musical', 'note', 'music', 'song', 'melody'] },
		{ emoji: '🎶', keywords: ['musical', 'notes', 'music', 'song', 'melody'] },
		{ emoji: '🎤', keywords: ['microphone', 'sing', 'karaoke', 'music', 'voice'] },
		{ emoji: '🎧', keywords: ['headphones', 'music', 'listen', 'audio', 'sound'] },
		{ emoji: '📱', keywords: ['mobile', 'phone', 'cell', 'smartphone', 'device'] },
		{ emoji: '💻', keywords: ['laptop', 'computer', 'pc', 'work', 'tech'] },
		{ emoji: '🖥️', keywords: ['desktop', 'computer', 'monitor', 'pc', 'work'] },
		{ emoji: '⌨️', keywords: ['keyboard', 'type', 'computer', 'input'] },
		{ emoji: '🖱️', keywords: ['mouse', 'computer', 'click', 'pointer'] },
		{ emoji: '📺', keywords: ['television', 'tv', 'watch', 'screen', 'entertainment'] },
		{ emoji: '📷', keywords: ['camera', 'photo', 'picture', 'snapshot'] },
		{ emoji: '📹', keywords: ['video', 'camera', 'record', 'film'] },
		{ emoji: '🔍', keywords: ['magnifying', 'glass', 'search', 'find', 'look'] },
		{ emoji: '🔎', keywords: ['magnifying', 'glass', 'tilted', 'search', 'examine'] },
		{ emoji: '💰', keywords: ['money', 'bag', 'cash', 'rich', 'wealth'] },
		{ emoji: '💳', keywords: ['credit', 'card', 'payment', 'money', 'purchase'] },
		{ emoji: '🎲', keywords: ['dice', 'game', 'gambling', 'chance', 'random'] },
		{ emoji: '🧩', keywords: ['puzzle', 'piece', 'solve', 'problem', 'solution'] },
		{ emoji: '❤️', keywords: ['love', 'heart', 'red', 'romance', 'affection'] },
		{ emoji: '🧡', keywords: ['orange', 'heart', 'love', 'warm', 'friendship'] },
		{ emoji: '💛', keywords: ['yellow', 'heart', 'love', 'friendship', 'happy'] },
		{ emoji: '💚', keywords: ['green', 'heart', 'love', 'nature', 'jealous'] },
		{ emoji: '💙', keywords: ['blue', 'heart', 'love', 'trust', 'loyalty'] },
		{ emoji: '💜', keywords: ['purple', 'heart', 'love', 'compassion', 'understanding'] },
		{ emoji: '🖤', keywords: ['black', 'heart', 'love', 'dark', 'evil'] },
		{ emoji: '🤍', keywords: ['white', 'heart', 'love', 'pure', 'clean'] },
		{ emoji: '🤎', keywords: ['brown', 'heart', 'love', 'earth', 'stability'] },
		{ emoji: '💔', keywords: ['broken', 'heart', 'love', 'sad', 'heartbreak'] },
		{ emoji: '❣️', keywords: ['heart', 'exclamation', 'love', 'affection', 'decoration'] },
		{ emoji: '💕', keywords: ['two', 'hearts', 'love', 'affection', 'romance'] },
		{ emoji: '💞', keywords: ['revolving', 'hearts', 'love', 'affection', 'romance'] },
		{ emoji: '💓', keywords: ['beating', 'heart', 'love', 'affection', 'alive'] },
		{ emoji: '💗', keywords: ['growing', 'heart', 'love', 'affection', 'excited'] },
		{ emoji: '💖', keywords: ['sparkling', 'heart', 'love', 'affection', 'excited'] },
		{ emoji: '💘', keywords: ['heart', 'arrow', 'love', 'cupid', 'romance'] },
		{ emoji: '💝', keywords: ['heart', 'box', 'love', 'gift', 'present'] },
		{ emoji: '💟', keywords: ['heart', 'decoration', 'love', 'purple', 'white'] },
	],
};
