export const data = {
	name: 'Smileys & People',
	emojis: [
		{ emoji: '😀', keywords: ['smile', 'happy', 'joy', 'grin', 'content'] },
		{ emoji: '😃', keywords: ['smile', 'happy', 'joy', 'grin', 'excited'] },
		{ emoji: '😄', keywords: ['smile', 'happy', 'joy', 'laugh', 'excited'] },
		{ emoji: '😁', keywords: ['smile', 'happy', 'grin', 'joy', 'teeth'] },
		{ emoji: '😆', keywords: ['laugh', 'happy', 'joy', 'excited', 'fun'] },
		{ emoji: '😅', keywords: ['laugh', 'sweat', 'nervous', 'awkward', 'relief'] },
		{ emoji: '😂', keywords: ['laugh', 'joy', 'tears', 'funny', 'hilarious'] },
		{ emoji: '🤣', keywords: ['laugh', 'rolling', 'funny', 'hilarious', 'tears'] },
		{ emoji: '😊', keywords: ['smile', 'happy', 'blush', 'shy', 'content'] },
		{ emoji: '😇', keywords: ['angel', 'innocent', 'halo', 'good', 'pure'] },
		{ emoji: '🙂', keywords: ['smile', 'happy', 'slight', 'content', 'ok'] },
		{ emoji: '🙃', keywords: ['upside', 'down', 'silly', 'sarcastic', 'ironic'] },
		{ emoji: '😉', keywords: ['wink', 'flirt', 'joke', 'secret', 'playful'] },
		{ emoji: '😌', keywords: ['relieved', 'peaceful', 'content', 'calm', 'zen'] },
		{ emoji: '😍', keywords: ['love', 'heart', 'eyes', 'adore', 'crush'] },
		{ emoji: '🥰', keywords: ['love', 'hearts', 'smiling', 'adore', 'affection'] },
		{ emoji: '😘', keywords: ['kiss', 'love', 'heart', 'blow', 'affection'] },
		{ emoji: '😗', keywords: ['kiss', 'whistle', 'lips', 'pucker', 'cute'] },
		{ emoji: '😙', keywords: ['kiss', 'smile', 'happy', 'content', 'affection'] },
		{ emoji: '😚', keywords: ['kiss', 'closed', 'eyes', 'love', 'peaceful'] },
		{ emoji: '😋', keywords: ['yum', 'tongue', 'delicious', 'tasty', 'food'] },
		{ emoji: '😛', keywords: ['tongue', 'playful', 'silly', 'tease', 'fun'] },
		{ emoji: '😝', keywords: ['tongue', 'wink', 'silly', 'playful', 'tease'] },
		{ emoji: '😜', keywords: ['tongue', 'wink', 'crazy', 'silly', 'playful'] },
		{ emoji: '🤪', keywords: ['crazy', 'wild', 'silly', 'fun', 'party'] },
		{ emoji: '🤨', keywords: ['raised', 'eyebrow', 'suspicious', 'doubt', 'questioning'] },
		{ emoji: '🧐', keywords: ['monocle', 'fancy', 'study', 'examine', 'curious'] },
		{ emoji: '🤓', keywords: ['nerd', 'glasses', 'geek', 'smart', 'study'] },
		{ emoji: '😎', keywords: ['cool', 'sunglasses', 'awesome', 'confident', 'chill'] },
		{ emoji: '🤩', keywords: ['star', 'struck', 'amazed', 'wow', 'excited'] },
		{ emoji: '🥳', keywords: ['party', 'celebrate', 'birthday', 'hat', 'fun'] },
		{ emoji: '😟', keywords: ['worried', 'sad', 'concerned', 'anxious', 'upset'] },
		{ emoji: '😔', keywords: ['sad', 'down', 'disappointed', 'dejected', 'pensive'] },
		{ emoji: '😞', keywords: ['disappointed', 'sad', 'upset', 'let', 'down'] },
		{ emoji: '😣', keywords: ['persevere', 'struggle', 'pain', 'effort', 'hard'] },
		{ emoji: '😖', keywords: ['confounded', 'confused', 'frustrated', 'annoyed'] },
		{ emoji: '😫', keywords: ['tired', 'exhausted', 'weary', 'fed', 'up'] },
		{ emoji: '😩', keywords: ['weary', 'tired', 'exhausted', 'frustrated', 'annoyed'] },
		{ emoji: '🥺', keywords: ['pleading', 'puppy', 'eyes', 'beg', 'please', 'cute'] },
		{ emoji: '😢', keywords: ['cry', 'sad', 'tears', 'weep', 'sorrow'] },
		{ emoji: '😭', keywords: ['loudly', 'crying', 'sob', 'tears', 'bawl'] },
		{ emoji: '😤', keywords: ['huffing', 'mad', 'angry', 'frustrated', 'steaming'] },
		{ emoji: '😠', keywords: ['angry', 'mad', 'annoyed', 'frustrated', 'grumpy'] },
		{ emoji: '😡', keywords: ['pouting', 'angry', 'mad', 'rage', 'furious'] },
		{ emoji: '🤬', keywords: ['swearing', 'cursing', 'angry', 'symbols', 'mad'] },
		{ emoji: '🤯', keywords: ['exploding', 'head', 'mind', 'blown', 'shocked'] },
		{ emoji: '😳', keywords: ['flushed', 'embarrassed', 'shy', 'blush', 'surprise'] },
		{ emoji: '🥵', keywords: ['hot', 'heat', 'sweat', 'burn', 'fever'] },
		{ emoji: '🥶', keywords: ['cold', 'freeze', 'chill', 'blue', 'frozen'] },
		{ emoji: '😱', keywords: ['scream', 'fear', 'shock', 'surprise', 'horror'] },
		{ emoji: '😨', keywords: ['fearful', 'scared', 'afraid', 'shock', 'surprise'] },
		{ emoji: '😰', keywords: ['anxious', 'sweat', 'nervous', 'worried', 'stress'] },
		{ emoji: '😥', keywords: ['sad', 'but', 'relieved', 'disappointed', 'whew'] },
		{ emoji: '😓', keywords: ['downcast', 'sweat', 'sad', 'tired', 'sorry'] },
		{ emoji: '🤗', keywords: ['hugging', 'hug', 'embrace', 'cuddle', 'love'] },
		{ emoji: '🤔', keywords: ['thinking', 'hmm', 'consider', 'pondering', 'wonder'] },
		{ emoji: '🤭', keywords: ['hand', 'over', 'mouth', 'giggle', 'oops', 'secret'] },
		{ emoji: '🤫', keywords: ['shh', 'quiet', 'silence', 'secret', 'hush'] },
		{ emoji: '🤥', keywords: ['lying', 'liar', 'pinocchio', 'dishonest', 'fib'] },
		{ emoji: '😶', keywords: ['no', 'mouth', 'mute', 'silence', 'quiet'] },
		{ emoji: '😐', keywords: ['neutral', 'expressionless', 'meh', 'blank', 'deadpan'] },
		{ emoji: '😑', keywords: ['expressionless', 'blank', 'meh', 'deadpan', 'whatever'] },
		{ emoji: '😬', keywords: ['grimacing', 'awkward', 'eek', 'yikes', 'cringe'] },
		{ emoji: '🙄', keywords: ['eye', 'roll', 'whatever', 'annoyed', 'duh'] },
		{ emoji: '😯', keywords: ['hushed', 'surprised', 'wow', 'amazed', 'gasp'] },
		{ emoji: '😦', keywords: ['frowning', 'open', 'mouth', 'surprised', 'concern'] },
		{ emoji: '😧', keywords: ['anguished', 'stunned', 'surprised', 'worried'] },
		{ emoji: '😮', keywords: ['open', 'mouth', 'surprised', 'wow', 'amazed'] },
		{ emoji: '😲', keywords: ['astonished', 'amazed', 'surprised', 'wow', 'gasp'] },
		{ emoji: '🥱', keywords: ['yawn', 'tired', 'sleepy', 'bored'] },
		{ emoji: '😴', keywords: ['sleeping', 'sleep', 'tired', 'zzz', 'rest'] },
		{ emoji: '🤤', keywords: ['drooling', 'sleep', 'hungry', 'desire', 'want'] },
		{ emoji: '😪', keywords: ['sleepy', 'tired', 'yawn', 'drowsy', 'exhausted'] },
		{ emoji: '😵', keywords: ['dizzy', 'confused', 'knocked', 'out', 'dead'] },
		{ emoji: '🤐', keywords: ['zipper', 'mouth', 'secret', 'sealed', 'quiet'] },
		{ emoji: '🥴', keywords: ['woozy', 'tipsy', 'drunk', 'confused', 'dizzy'] },
		{ emoji: '🤢', keywords: ['nauseated', 'sick', 'ill', 'green', 'vomit'] },
		{ emoji: '🤮', keywords: ['vomiting', 'sick', 'throw', 'up', 'puke'] },
		{ emoji: '🤧', keywords: ['sneezing', 'gesundheit', 'sick', 'allergies'] },
		{ emoji: '😷', keywords: ['mask', 'sick', 'ill', 'doctor', 'health'] },
		{ emoji: '🤒', keywords: ['thermometer', 'sick', 'fever', 'ill', 'temperature'] },
		{ emoji: '🤕', keywords: ['bandaged', 'head', 'hurt', 'injury', 'hospital'] },
	],
};
