export const data = {
	name: 'Transports',
	emojis: [
		{ emoji: '🚗', keywords: ['car', 'automobile', 'vehicle', 'drive', 'road'] },
		{ emoji: '🚕', keywords: ['taxi', 'cab', 'yellow', 'ride', 'transport'] },
		{ emoji: '🚙', keywords: ['sport', 'utility', 'vehicle', 'suv', 'car'] },
		{ emoji: '🚌', keywords: ['bus', 'public', 'transport', 'vehicle', 'travel'] },
		{ emoji: '🚎', keywords: ['trolleybus', 'bus', 'electric', 'public', 'transport'] },
		{ emoji: '🏎️', keywords: ['racing', 'car', 'fast', 'speed', 'formula'] },
		{ emoji: '🚓', keywords: ['police', 'car', 'cop', 'law', 'enforcement'] },
		{ emoji: '🚑', keywords: ['ambulance', 'emergency', 'medical', 'hospital'] },
		{ emoji: '🚒', keywords: ['fire', 'engine', 'truck', 'emergency', 'rescue'] },
		{ emoji: '🚐', keywords: ['minibus', 'van', 'transport', 'vehicle'] },
		{ emoji: '🛻', keywords: ['pickup', 'truck', 'vehicle', 'transport'] },
		{ emoji: '🚛', keywords: ['articulated', 'lorry', 'truck', 'cargo', 'freight'] },
		{ emoji: '🚜', keywords: ['tractor', 'farm', 'agriculture', 'vehicle'] },
		{ emoji: '🏍️', keywords: ['motorcycle', 'bike', 'motorbike', 'vehicle'] },
		{ emoji: '🛵', keywords: ['motor', 'scooter', 'vespa', 'bike', 'vehicle'] },
		{ emoji: '🚲', keywords: ['bicycle', 'bike', 'cycle', 'pedal', 'exercise'] },
		{ emoji: '🛴', keywords: ['kick', 'scooter', 'ride', 'fun', 'transport'] },
		{ emoji: '🛹', keywords: ['skateboard', 'skate', 'board', 'sport', 'ride'] },

		{ emoji: '🚁', keywords: ['helicopter', 'chopper', 'aircraft', 'fly', 'rotor'] },
		{ emoji: '🛸', keywords: ['flying', 'saucer', 'ufo', 'alien', 'space'] },
		{ emoji: '✈️', keywords: ['airplane', 'plane', 'aircraft', 'fly', 'travel'] },
		{ emoji: '🛩️', keywords: ['small', 'airplane', 'plane', 'aircraft', 'private'] },
		{ emoji: '🛫', keywords: ['airplane', 'departure', 'takeoff', 'travel', 'fly'] },
		{ emoji: '🛬', keywords: ['airplane', 'arrival', 'landing', 'travel', 'fly'] },

		{ emoji: '🚀', keywords: ['rocket', 'space', 'launch', 'fast', 'blast'] },
		{ emoji: '🛰️', keywords: ['satellite', 'space', 'orbit', 'communication'] },
		{ emoji: '🚂', keywords: ['locomotive', 'train', 'steam', 'railway'] },
		{ emoji: '🚆', keywords: ['train', 'railway', 'transportation', 'travel'] },
		{ emoji: '🚄', keywords: ['high', 'speed', 'train', 'bullet', 'fast'] },
		{ emoji: '🚅', keywords: ['bullet', 'train', 'fast', 'japan', 'speed'] },
		{ emoji: '🚈', keywords: ['light', 'rail', 'train', 'metro', 'urban'] },
		{ emoji: '🚝', keywords: ['monorail', 'train', 'transportation'] },
		{ emoji: '🚞', keywords: ['mountain', 'railway', 'train', 'scenic'] },
		{ emoji: '🚋', keywords: ['tram', 'car', 'streetcar', 'public', 'transport'] },
		{ emoji: '🚃', keywords: ['railway', 'car', 'train', 'carriage'] },
		{ emoji: '🚟', keywords: ['suspension', 'railway', 'train', 'monorail'] },
		{ emoji: '🚠', keywords: ['mountain', 'cableway', 'ski', 'lift'] },
		{ emoji: '🚡', keywords: ['aerial', 'tramway', 'cable', 'car', 'mountain'] },
		{ emoji: '🛤️', keywords: ['railway', 'track', 'train', 'rails'] },
		{ emoji: '🚇', keywords: ['metro', 'subway', 'underground', 'train', 'urban'] },
		{ emoji: '🛳️', keywords: ['passenger', 'ship', 'cruise', 'boat', 'ocean'] },
		{ emoji: '⛵', keywords: ['sailboat', 'boat', 'sailing', 'yacht', 'wind'] },
		{ emoji: '🚤', keywords: ['speedboat', 'boat', 'fast', 'water', 'motor'] },
		{ emoji: '🛥️', keywords: ['motor', 'boat', 'yacht', 'luxury', 'water'] },
		{ emoji: '🚢', keywords: ['ship', 'boat', 'cruise', 'ocean', 'travel'] },
		{ emoji: '⚓', keywords: ['anchor', 'ship', 'boat', 'sea', 'port'] },
		{ emoji: '🛟', keywords: ['ring', 'buoy', 'life', 'saver', 'rescue'] },
		{ emoji: '🚧', keywords: ['construction', 'sign', 'warning', 'work', 'road'] },
		{ emoji: '⛽', keywords: ['fuel', 'pump', 'gas', 'station', 'petrol'] },
		{ emoji: '🚨', keywords: ['police', 'car', 'light', 'siren', 'emergency'] },
		{ emoji: '🚥', keywords: ['horizontal', 'traffic', 'light', 'signal', 'stop'] },
		{ emoji: '🚦', keywords: ['vertical', 'traffic', 'light', 'signal', 'stop'] },
		{ emoji: '🛣️', keywords: ['motorway', 'highway', 'road', 'travel'] },
		{ emoji: '🗺️', keywords: ['world', 'map', 'geography', 'travel', 'navigation'] },

		{ emoji: '🚩', keywords: ['triangular', 'flag', 'post', 'warning', 'mark'] },
	],
};
