export const ACTION = {
	APPLY_RULE: 'applyRule',
	UNGROUP_TAB: 'ungroupTab',
	OPEN_PROMPT: 'openPrompt',
	SET_PINNED: 'setPinned',
	SET_UNIQUE: 'setUnique',
	SET_PROTECTED: 'setProtected',
	RENAME_TAB: 'renameTab',
	SET_GROUP: 'setGroup',
	SET_MUTED: 'setMuted',
	SET_ICON: 'setIcon',
	SET_TAB_COLOR: 'setTabColor',
	SET_TAB_GROUP_COLOR: 'setTabGroupColor',
	SET_TAB_GROUP_ICON: 'setTabGroupIcon',
	SET_TAB_GROUP_PINNED: 'setTabGroupPinned',
	SET_TAB_GROUP_PROTECTED: 'setTabGroupProtected',
	SET_TAB_GROUP_UNIQUE: 'setTabGroupUnique',
	SWITCH_TAB_GROUP: 'switchTabGroup',
};
